### ISSUE TITLE
Understanding the state of an stream provider depending on a future provider

### ISSUE THREAD

**Issue by erf** [rrousselGit/river_pod#272]
**Describe what scenario you think is uncovered by the existing examples/articles**

If i have a `StreamProvider` “A” that watches and depends on a `FutureProvider` “B” , is the resulting type of watching “A” entirely dependent on the state of “B”, so that i only need to return valid data, if “B” returns a type of `AsyncData` and ignore the other cases? That is, it does not matter what value i return in the case of AsyncLoading or AsyncError, as these are handled when "A" is watched? If so, it feels a bit weird to return a value that is never used.

I think this was a bit confusing to understand, and maybe i need to understand better how `watch` works. If someone could enlighten me a bit on these topics or point me to some documentation that would be great. Thanks.

Example:

```
final B = FutureProvider((ref) async {
  return await getSomeData();
})

final A = StreamProvider<List<Item>>((ref) {
  final asyncVal = ref.watch(B);
  if (asyncVal is AsyncData) {
    return subscribeToSomeStreamGivenId(asyncVal.data.value.id);
  }
  return Stream.value([]); // THIS IS IGNORED !

/**
  // which would be similar to this
  return asyncVal.when(
    data: (data) => subscribeToSomeStreamGivenId(data.value.id);
    loading: () => Stream.value([]),  // THIS IS IGNORED !
    error: (error, stack) => Stream.value([]),  // THIS IS IGNORED !
  );
*/
}
final val = watch(A)
```

**Describe why existing examples/articles do not cover this case**

I read the "Getting started guide" and the docs including `ProviderReference` etc.

**Additional context**

**Comment by rrousselGit** [comment]
Maybe you don't want to read the `AsyncValue` and instead want the future?

```dart
final B = FutureProvider((ref) async {
  return await getSomeData();
})

final A = StreamProvider<List<Item>>((ref) async* {
  final asyncVal = await ref.watch(B.future);

  yield* subscribeToSomeStreamGivenId(asyncVal.id);
});
```

**Comment by erf** [comment]
Ah thanks. I did not know about `B.future`. If `B` was a stream, would you use `B.last`?

**Comment by erf** [comment]
When i tried to subscribe to a a stream using:

```
final A = StreamProvider<List<Plan>>((ref) async* {
  final asyncVal = await ref.watch(B.future);

  yield* subscribeToSomeStreamGivenId(asyncVal.id);
});
```

And then trying to listen to `A.last` like:

```
final B = FutureProvider.autoDispose<Plan>((ref) async {
  final plans = await ref.watch(A.last);
// TODO return plan
});
```

And `A.last` return an empty list or null i get `Bad state: no element`

**Comment by erf** [comment]
I noticed when the i watched `stream.last` and the stream was empty, i got an exception `bad state: no elements`.

**Comment by erf** [comment]
How can i return an empty stream for the the proivder A if asyncVal is null?

**Comment by erf** [comment]
I figured out i can do: `yield* Stream.empty()` but i noticed when i return `empty` and use `autoDispose` the provider was rebuilt every time. 

Anyways, i will close this now, as this issue is not very focused.

**Comment by rrousselGit** [comment]
I've fixed the bad state error you previously mentioned, so you should be able to use `.last`

**Comment by erf** [comment]
That's great!

**Comment by erf** [comment]
I still experienced an exception in the latest release. Although now with another exception message. I created a new issue for this #301
