### ISSUE TITLE
Providers with .autoDispose are not recreated after been disposed

### ISSUE THREAD

**Issue by julienlebren** [rrousselGit/river_pod#579]
I don't know if it's due to riverpod 1.0.0, but I did several changes since the migration and I can't revert back to 0.14 to test if the bug was already here or not.

My `StateNotifierProvider.autoDispose` are not disposed when popping the view.
When I come back inside the view, the provider is not re-created, it uses the previous one.

The issue occurs with all the providers, not in a specific view.
Here is an example but it may be difficult to reproduce because it uses a lot of custom classes not included in this sample code:

```dart
final settingsAppearanceControllerProvider = StateNotifierProvider.autoDispose<
    SettingsAppearanceController, SnapFormState>((ref) {
  print("settingsAppearanceControllerProvider has been created");
  final repository = ref.watch(profileRepositoryProvider);
  return SettingsAppearanceController(repository!);
});

void _handleEvent(WidgetRef ref, SettingsAppearanceEvent event) {
  final controller = ref.read(settingsAppearanceControllerProvider.notifier);
  final profile = ref.read(profileProvider);
  controller.handleFormEvent(profile!, event);
}

class SettingsAppearancePage extends ConsumerWidget {
  const SettingsAppearancePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final l10n = ref.read(localizationProvider);
    return SettingsPageBuilder(
      provider: settingsAppearanceControllerProvider,
      title: l10n.settingsAppearanceTitle,
      child: FormPage(
        children: [
          const SettingsAppearanceThemeSection(),
        ],
      ),
    );
  }
}

final themeTypeProvider =
    Provider.autoDispose<ThemeType>((ref) => ref.watch(profileProvider)!.theme);

class SettingsAppearanceThemeSection extends ConsumerWidget {
  const SettingsAppearanceThemeSection({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final l10n = ref.read(localizationProvider);
    return FormSection(
      title: l10n.settingsAppearanceThemeSectionTitle,
      children: [
        for (ThemeType theme in ThemeType.values)
          ProviderScope(
            overrides: [
              _currentTheme.overrideWithValue(theme),
            ],
            child: const SettingsAppearanceThemeRow(),
          ),
      ],
      caption: l10n.settingsAppearanceThemeSectionCaption,
    );
  }
}

final _currentTheme = Provider<ThemeType>((ref) {
  throw UnimplementedError();
});

class SettingsAppearanceThemeRow extends ConsumerWidget {
  const SettingsAppearanceThemeRow({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final selectedTheme = ref.watch(themeTypeProvider);
    final theme = ref.watch(_currentTheme);
    return FormTappableField(
      value: theme.description(ref),
      showDisclosureIndicator: false,
      showSelectedIndicator: (theme == selectedTheme),
      onPressed: () => _handleEvent(
        ref,
        SettingsAppearanceEvent.themeChanged(theme),
      ),
    );
  }
}
```

When I pop the view and come back in it, "settingsAppearanceControllerProvider has been created" is not printed in the console. 

It's just an example between a lot of other use cases, but none of my autoDisposed providers are disposed.

**Comment by wujek-srujek** [comment]
I've also updated to 1.0.0-dev.2 and I've just made a quick test and everything works fine in my case, the providers get disposed and recreated again when necessary.

**Comment by julienlebren** [comment]
I did some tests and some other providers are disposed... but not this one and I don't understand why.
@rrousselGit is there some debug feature that allow us to see which watcher/listener is retaining the provider?

**Comment by julienlebren** [comment]
This issue is driving me crazy. 
I reduced by code to the simplest to find which is generating this problem.

The current code is:
```dart
final testProvider = StateProvider.autoDispose<bool>((ref) {
  print("testProvider has been created");
  return true;
});

class SettingsAppearancePage extends ConsumerWidget {
  const SettingsAppearancePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final test = ref.watch(testProvider);
    return Center(
      child: TextButton(
        child: Text("value is ${test.state}"),
        onPressed: () => ref.read(testProvider).state = !test.state,
      ),
    );
  }
```

With this short code, when I pop the view then enter again, this error is raised:
`Bad state: Tried to use StateController<bool> after `dispose` was called.`

`testProvider` is not recreated 🤯

**Comment by julienlebren** [comment]
I found a workaround by pushing the view like this:
```dart
MaterialPageRoute<dynamic>(
  builder: (_) => ProviderScope(
    child: const SettingsAppearancePage(),
  ),
);
```
instead of like this:
```dart
MaterialPageRoute<dynamic>(
  builder: (_) => const SettingsAppearancePage(),
);
```

But I don't understand why I need this.
I'm using nested navigation with tabs, I will look into this direction.
I've known better sundays 🙃

**Comment by wujek-srujek** [comment]
How do you actually know that it isn't disposed and that this is the issue? The error message isn't saying this at all.  What happens when you have:
```dart
final testProvider = StateProvider.autoDispose<bool>((ref) {
  print("testProvider has been created");
  ref.onDispose(() {
    print('disposing');
  });
  return true;
});
```
Do you ever see 'disposing' in the output?

**Comment by julienlebren** [comment]
> Do you ever see 'disposing' in the output?

Good shot, yes I see it.

But when entering again in the view:
```
Bad state: Tried to use StateController<bool> after 'dispose' was called.

Consider checking 'mounted'.
````

It does not happen if the view is pushed with a new `ProviderScope`.
I think this is a nested navigation related issue...

**Comment by wujek-srujek** [comment]
Right, so I guess you need a new bug, with a better title ;d

**Comment by julienlebren** [comment]
Ok after running some tests, the providers are disposed, no problem with this.
But they are not recreated when needing them again.

The most curious is that in the view, values shown are those from the first provider (which is supposed to be disposed at the time the view is displayed 🤪).

**Comment by wujek-srujek** [comment]
In my tests I mentioned in https://github.com/rrousselGit/river_pod/issues/579#issuecomment-873457914 I see no issue with this either, the new state is created.

**Comment by julienlebren** [comment]
As I mentioned, I don't have this issue everywhere in my app, but in some parts only...
But the app is complex with tabs, nested navigators, full dialog routes, etc.

I would like to understand why a `ProviderScope` solves the issue whereas it's not needed at other places in the app.
I will continue to dig this issue this afternoon...

**Comment by wujek-srujek** [comment]
`ProviderScope` fixes it because this way the provider state is put into this scope; when you pop, the provider and the scope that contained its state is destroyed, and when you push again, you create a fresh scope, a completely unrelated instance, which can't possibly know about the old state. At least this is my understanding of scopes.

Do you happen to have https://riverpod.dev/docs/concepts/modifiers/auto_dispose/#refmaintainstate used anywhere?

**Comment by rrousselGit** [comment]
If you have a minimal reproducible example, I can have a look.

**Comment by julienlebren** [comment]
I was cleaning the code to isolate the issue to provide you a minimal reproducible example... and the issue was not here. 
So I spent hours to add/remove part by part to isolate the part which is "building" the issue.

And this is it:
```dart
    MaterialApp(
      navigatorKey: NavigatorKeys.main,
      localizationsDelegates: AppLocalizations.localizationsDelegates,
      supportedLocales: AppLocalizations.supportedLocales,
      initialRoute: AppRoutes.testPage,
      onGenerateRoute: AppRouter.onGenerateRoute,
      builder: (context, child) {
        return ProviderScope(
          overrides: [
            localizationProvider
                .overrideWithValue(AppLocalizations.of(context)!),
          ],
          child: child!,
        );
      },
    );
```

The `ProviderScope` that I pass to the `builder` param of my `MaterialApp` is causing the trouble.

This is probably a misunderstanding on my part when using `ProviderScope` but I have the same understanding as @wujek-srujek [mentioned here](https://github.com/rrousselGit/river_pod/issues/579#issuecomment-873567606). 
So I don't understand why this `ProviderScope` in the builder causes troubles deeper in the app.

**Comment by rrousselGit** [comment]
In all honestly, I have a hard time understanding the relationship between this new snippet and the context of the issue.

**Comment by julienlebren** [comment]
However, here is the sample code of the test:

```dart
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(
    ProviderScope(
      child: const TestApp(),
    ),
  );
}

lass Router {
  static Route<dynamic>? onGenerateRoute(RouteSettings settings) {
    return MaterialPageRoute(
      builder: (_) => TestPage(),
    );
  }
}

final testProvider = Provider<bool>((_) => false);

final anotherProvider = StateProvider.autoDispose<bool>((_) => true);

class TestApp extends StatelessWidget {
  const TestApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      onGenerateRoute: Router.onGenerateRoute,
      builder: (context, child) {
        return ProviderScope(
          overrides: [
            testProvider.overrideWithValue(true),
          ],
          child: child!,
        );
      },
    );
  }
}

class TestPage extends StatelessWidget {
  const TestPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      child: Center(
        child: TextButton(
          child: Text("Move to next view"),
          onPressed: () {
            Navigator.push(
              context,
              MaterialPageRoute(builder: (context) => SecondPage()),
            );
          },
        ),
      ),
    );
  }
}

class SecondPage extends ConsumerWidget {
  const SecondPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final test = ref.watch(testProvider);
    final another = ref.watch(anotherProvider);
    print("Building SecondPage");

    return Center(
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          TextButton(
            child: Text("values are $test and ${another.state}"),
            onPressed: () => ref.read(anotherProvider).state = !another.state,
          ),
          TextButton(
            child: Text("Back to first view"),
            onPressed: () {
              Navigator.of(context).pop();
            },
          ),
        ],
      ),
    );
  }
}
```

If you move to the next view, pop then open it again, you will have an error.
If you remove the `builder` param of `MaterialApp` which includes a `ProviderScope`, it will work.

**Comment by rrousselGit** [comment]
I see, thanks!

This is a bug, I will investigate.

**Comment by julienlebren** [comment]
I can't be happy that this is a bug, but it still is comfortable since it means that you are going to dig into the problem 🙃

**Comment by rrousselGit** [comment]
I have found the problem. But it is a tricky one, which showcased other bugs.
It probably will take a bit of time to fix

**Comment by julienlebren** [comment]
No worries, I will do some workaround while the bug is not fixed, to avoid using `ProviderScope` in the `builder` param of `MaterialApp`.
Just for information, is it a bug in 1.0.0 exclusively or did I miss it when I was using 0.14?

**Comment by rrousselGit** [comment]
This is a regression caused by the scoping mechanism

**Comment by rrousselGit** [comment]
Fixed in 1.0.0-dev.3

**Comment by Drkstr** [comment]
I am still seeing this bug in 1.03 :( 

Is there anything I need to do to recreate an auto disposed StateNotifierProvider?

**Comment by arcas0803** [comment]
Still seeing this bug.
I tried to create a stateNotifier with autoDispose and not working.
Also tried to call stateNotifier dispose() when navigation and the provider disposes, but preserve state and not reload.

**Comment by hunterpp** [comment]
I'm thinking I may be seeing the same bug, but not sure:
```
final pittieProvider = StateNotifierProvider<DogStateNotifier, DogState>((ref) {
  ref.onDispose(() {
    log("DISPOSED causes error");
  });
  return ref.read(dogStateProvider(DogType.pittie).notifier);
});

final simplePittieProvider =
    StateNotifierProvider<DogStateNotifier, DogState>((ref) {
  ref.onDispose(() {
    log("DISPOSED SIMPLE no error");
  });
  return PittieNotifier();
});

final dogStateProvider =
    StateNotifierProvider.family<DogStateNotifier, DogState, DogType>(
        (ref, type) {
  ref.onDispose(() {
    log("DISPOSED DSP");
  });
  if (type == DogType.pittie) {
    PittieNotifier pittieNotifier = PittieNotifier();
    pittieNotifier.startDog;
    return pittieNotifier;
  } else {
    return PittieNotifier();
  }
});
```

In above code from https://github.com/hunterpp/riverpod_child_provider/blob/main/lib/dogs.dart, when pullToRefresh happens here: https://github.com/ftognetto/riverpod_infinite_scroll/blob/80c076c34fa26ff2e3da4be81d1602c755e83146/lib/src/river_paged_builder.dart#L183  it errors with pittieProvider as shown below: 
![Screen Shot 2022-07-01 at 3 21 14 AM](https://user-images.githubusercontent.com/772917/176984396-0443057b-1135-4463-8947-3ae1c21a116f.png)

However, it does not error with `simplePittieProvider` (i've tried ref.read, ref.watch) also tried riverpod 2.0.0-dev9 and same error still occurs

any idea why? both pittieProvider and simplePittieProvider call onDispose yet only pittieProvider errors.

**Comment by acheronian** [comment]
Having the same issues as @arcas0803 
+1

**Comment by rrousselGit** [comment]
This is a closed issue. If you face a problem similar to this, please open a new issue with a description of the bug and steps to reproduce it.

The bug described in this issue was fixed, so if you still have the problem, that's most definitely a different scenario.

**Comment by lwj1994** [comment]
still seeing in 1.0.4. I'm not in the mood to create new issue，terrible experience @rrousselGit

**Comment by Sultan-dev** [comment]
I think I am facing the same issue with `FutureProvider`, the widget doesn't display the new data in the provider.
My provider is retrieving some data from firestore, once there is an item added and i switch to this screen, it doesn't show the new item. So, my temporary solution is to refresh the screen.

`flutter doctor -v` log:
<details>
  <summary>Click me</summary>

 ```
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.0.1 22A400 darwin-arm, locale
    en-SA)
    • Flutter version 3.3.10 on channel stable at
      /Users/s_alkhubayzi/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (3 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/s_alkhubayzi/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12
      (API 32) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS
      13.0.1 22A400 darwin-arm
    • Chrome (web)                • chrome        • web-javascript • Google
      Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
 ```
</details>

`pubspec.yaml` log:

<details>
  <summary>Click me</summary>
  
```
cupertino_icons: ^1.0.5
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.0.15
  connectivity_plus: ^3.0.2
  http: ^0.13.5
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.4
  url_launcher: ^6.1.7
  cached_network_image: ^3.2.3
  uuid: ^3.0.7
  google_sign_in: ^5.4.2
  firebase_messaging: ^14.2.1
  cloud_firestore: ^4.3.1
  pdf_render: ^1.3.6
  flutter_local_notifications: ^9.9.1
  cloud_functions: ^4.0.7
  sign_in_with_apple: ^4.3.0
  crypto: ^3.0.2
  rate_my_app: ^1.1.3
  share_plus: ^6.3.0
  firebase_crashlytics: ^3.0.9
  dropdown_search: ^5.0.5
  firebase_analytics: ^10.1.0
  firebase_remote_config: ^3.0.9
  package_info_plus: ^3.0.2
  simple_animations: ^5.0.0+3
  firebase_storage: ^11.0.10
  flutter_riverpod: ^2.1.3

dev_dependencies:
  build_runner: ^2.3.3
  riverpod_generator: ^1.1.1
  flutter_test:
    sdk: flutter

dependency_override:
  intl: ^0.17.0
```
  </details>

sample code:
```
final offersFuture = FutureProvider.autoDispose<List<Offer>>((ref) async {
  final firestore = ref.watch(firestoreProvider);
  return await firestore.getOffers();
});


@override
  Widget build(BuildContext context) {
    final auth = ref.read(authProvider);
    final connected = ref.watch(connectionProvider).connected;
    final offersAsync = ref.watch(offersFuture);
    return GestureDetector(
      onTap: () {
        FocusScope.of(context).unfocus();
      },
      child: Padding(
        padding: const EdgeInsets.all(12.0),
        child: offersAsync.when(
          data: (offers) {
            if (offers.length == 0) {
              return RefreshIndicator(
                onRefresh: () async {
                  ref.invalidate(offersFuture);
                },
                child: SingleChildScrollView(
                  physics: AlwaysScrollableScrollPhysics(),
                  child: Container(
                    height: MediaQuery.of(context).size.height,
                    width: MediaQuery.of(context).size.width,
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        Icon(
                          Icons.error_outline_outlined,
                          color: AppColor.grey,
                          size: 32,
                        ),
                        SizedBox(height: 10),
                        Text(
                          '${AppLocale.of(context).tr('errors.no_offers')}',
                          style: Theme.of(context)
                              .textTheme
                              .headline6!
                              .copyWith(color: AppColor.grey),
                        ),
                        auth.obj is Customer
                            ? CustomTextButton(
                                label:
                                    '${AppLocale.of(context).tr('buttons.marr')}',
                                onPressed: () {
                                  Navigator.of(context)
                                      .pushReplacementNamed(Routes.reg_mandoob);
                                },
                              )
                            : Container(),
                      ],
                    ),
                  ),
                ),
              );
            }
            return RefreshIndicator(
              onRefresh: () async {
                ref.invalidate(offersFuture);
              },
              child: ListView.separated(
                physics: AlwaysScrollableScrollPhysics(),
                itemCount: offers.length,
                itemBuilder: (BuildContext context, int index) {
                  return CustomCardOffer(
                    resName: offers[index].resName,
                    deliveryTime: DateFormat('hh:mma')
                        .format(offers[index].deliveredAt.toLocal()),
                    fee: offers[index].fee,
                    onTap: () {
                      if (connected) {
                        if (auth.obj != null) {
                          Navigator.of(context).pushNamed(
                            Routes.order_creation,
                            arguments: offers[index],
                          );
                        } else {
                          Navigator.of(context)
                              .pushReplacementNamed(Routes.login);
                        }
                      } else {
                        CustomSnackbar.showSnackBarError(
                            context, 'errors.connection_failed');
                      }
                    },
                  );
                },
                separatorBuilder: (BuildContext context, int index) {
                  return Divider(thickness: 0, color: Colors.white);
                },
              ),
            );
          },
          error: (error, stackTrace) {
            return Center(
              child: Text(
                '${AppLocale.of(context).tr('errors.went_wrong')}',
                style: Theme.of(context).textTheme.headline6,
              ),
            );
          },
          loading: () {
            return Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                crossAxisAlignment: CrossAxisAlignment.center,
                children: [
                  CircularProgressIndicator(),
                  SizedBox(height: 10),
                  Text(
                    '${AppLocale.of(context).tr('loading')}',
                    style: Theme.of(context).textTheme.headline6,
                  ),
                ],
              ),
            );
          },
        ),
      ),
    );
```

**Comment by BenjiFarquhar** [comment]
Is my issue the same?

An autoDispose StateNotifier is becoming unmounted and remaining that way after I cause my widget to rebuild by resizing the web browser window, causing a different layout in my page to display.
