### ISSUE TITLE
`Cannot use ref functions after the dependency of a provider changed but before the provider rebuilt` occurs under certain conditions

### ISSUE THREAD

**Issue by mono0926** [rrousselGit/river_pod#815]
**Describe the bug**

After https://github.com/rrousselGit/river_pod/commit/293cc06b21adf1d737fab8f405b79ea20b0c8bae was released, `Cannot use ref functions after the dependency of a provider changed but before the provider rebuilt` occurs under certain conditions

**To Reproduce**

It reproduced on our internal project, and I haven't been able to create a simple reproducible sample code yet 🙏 

I observed this:

```dart
ref.watch(fooProvider);
ref.watch(barProvider); // The error occurs under certain conditions.
```

- `ref.watch(fooProvider);` is called
- `_dependents` has `this`: https://github.com/rrousselGit/river_pod/blob/3a4637025ca9e7f30ee1c61fc9e7976e04415644/packages/riverpod/lib/src/framework/base_provider.dart#L935
- `element.getExposedValue()` in `watch` called: https://github.com/rrousselGit/river_pod/blob/f410a75dc1ae8c665c9db9a4b2bdd63d4b49faa5/packages/riverpod/lib/src/framework/base_provider.dart#L940-L940
- `_dependents[i]` has `this` and `_didChangeDependency()` called: https://github.com/rrousselGit/river_pod/blob/f410a75dc1ae8c665c9db9a4b2bdd63d4b49faa5/packages/riverpod/lib/src/framework/base_provider.dart#L795-L795
- `_debugDidChangeDependency` was set to `true`
- `ref.watch(fooProvider);` ended
- `ref.watch(barProvider);` called
- The assertion error occurs here because `_debugDidChangeDependency` was set to true: https://github.com/rrousselGit/river_pod/blob/f410a75dc1ae8c665c9db9a4b2bdd63d4b49faa5/packages/riverpod/lib/src/framework/base_provider.dart#L860-L860

**Expected behavior**

Works fine without any errors.

**Comment by rrousselGit** [comment]
Hello! 

Without a way to reproduce this, I have no means to K ow if that error is expected or not

**Comment by tomoyuki28jp** [comment]
My app uses the latest version of riverpod on master branch, but it sometimes throws this error :(

**Comment by rrousselGit** [comment]
@tomoyuki28jp could you share a way to reproduce the problem in your case?

I don't have the issue on master.

**Comment by Ethras** [comment]
Facing the same issue randomly on 1.0.0-dev.11. But seems to be fixed on master branch

**Comment by mono0926** [comment]
With https://github.com/rrousselGit/river_pod/issues/815#issuecomment-951819972 code and this, the error occurs on 1.0.0 stable release.

```dart
void main() {
  runApp(
    const ProviderScope(
      child: MaterialApp(
        home: FirstScreen(),
      ),
    ),
  );
}
````

1. Tap `Push First` button
2. Tap `Push Second` button
3. The error occurs
4. The navigation is done successfully

The error message is `Cannot use ref functions after the dependency of a provider changed but before the provider rebuilt`, but the log isn't printed at Console 🤔 

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/1255062/140675527-db1eb01d-13db-45bd-86a0-cf0730bcb05c.png">

**Comment by tbm98** [comment]
my issue #831 no longer exists. maybe your issue and mine are not the same

**Comment by chunghha** [comment]
I see same exception. For my use case, the exception happens only once while redirecting to a path with go_router while app alive. Here is to reproduce the exception below. https://github.com/chunghha/fl_pages/commit/f6bb92c8597076e79d3e909d98621b186e94d931 

I may be probably missing to check something so keep digging in but also I'd like to share for a help. 

```bash
Performing hot restart...                                               
Restarted application in 571ms.
flutter: GoRouter: known full paths for routes:
flutter: GoRouter:   => /
flutter: GoRouter:   => /polygon
flutter: GoRouter:   => /login
flutter: GoRouter: setting initial location /
flutter: |.. _routeToPath: /
flutter: \.... _authStatus: AuthStatus.unauthenticated
flutter: GoRouter: redirecting to /login
flutter: |.. _routeToPath: /login
flutter: \.... _authStatus: AuthStatus.unauthenticated
flutter: |.. _routeToPath: /login
flutter: \.... _authStatus: AuthStatus.unauthenticated
flutter: token 0002BIhGyCWXtb0YpIeRvED8TZ6R
flutter: \^[[38;5;12m┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
flutter: \^[[38;5;12m│ #0   printAppVersion (package:fl_pages/util/app_version.dart:12:13)<…>
flutter: \^[[38;5;12m│ #1   <asynchronous suspension><…>
flutter: \^[[38;5;12m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
flutter: \^[[38;5;12m│ 💡 App Version: 1.1.0+1.1.0<…>
flutter: \^[[38;5;12m└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
flutter: GoRouter: going to /
flutter: ══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═════════════════════════════════════════════════════════
flutter: The following _Exception was thrown Exception during GoRouter navigation:
flutter: Exception: 'package:riverpod/src/framework/provider_base.dart': Failed assertion: line 645 pos 7:
flutter: '_debugDidChangeDependency == false': Cannot use ref functions after the dependency of a provider
flutter: changed but before the provider rebuilt
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      ProviderElementBase._assertNotOutdated (package:riverpod/src/framework/provider_base.dart:645:7)
flutter: #3      ProviderElementBase.watch (package:riverpod/src/framework/provider_base.dart:691:5)
flutter: #4      appRouter.<anonymous closure>.<anonymous closure> (package:fl_pages/app.router.dart:49:15)
flutter: #5      GoRouterDelegate._getLocRouteMatchesWithRedirects (package:go_router/src/go_router_delegate.dart:323:22)
flutter: #6      GoRouterDelegate._go (package:go_router/src/go_router_delegate.dart:249:21)
flutter: #7      GoRouterDelegate.go (package:go_router/src/go_router_delegate.dart:149:5)
flutter: #8      GoRouter.go (package:go_router/src/go_router.dart:78:22)
flutter: #9      GoRouterHelper.go (package:go_router/go_router.dart:32:25)
flutter: #10     goToPage (package:fl_pages/app.router.dart:87:11)
flutter: #11     LoginButton.build.<anonymous closure> (package:fl_pages/widgets/login_button.widget.dart:39:11)
flutter: <asynchronous suspension>
flutter: (elided 2 frames from class _AssertionError)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: GoRouter: known full paths for routes:
flutter: GoRouter:   => /
flutter: GoRouter:   => /polygon
flutter: GoRouter:   => /login
flutter: GoRouter: setting initial location /
flutter: |.. _routeToPath: /
flutter: \.... _authStatus: AuthStatus.authenticated
flutter: GoRouter: refreshing /
flutter: |.. _routeToPath: /
flutter: \.... _authStatus: AuthStatus.authenticated
flutter: |.. _index onTap: 1
flutter: GoRouter: going to /polygon
flutter: |.. _routeToPath: /polygon
flutter: \.... _authStatus: AuthStatus.authenticated
flutter: |.. _index onTap: 0
flutter: GoRouter: going to /
flutter: |.. _routeToPath: /
flutter: \.... _authStatus: AuthStatus.authenticated
Application finished.
```

**Comment by chunghha** [comment]
I have my [fix](https://github.com/chunghha/fl_pages/commit/5b8ed493dd12e5fafd8eb4813fa5e614b5fd1f7c)

**Comment by rrousselGit** [comment]
For reference, this should be fixed in the 2.0.0 dev release.

**Comment by pcelis19** [comment]
> For reference, this should be fixed in the 2.0.0 dev release.

Do you know where I can find the notes for `2.0.0-dev.0` because I am still getting the same issue:

```bash
'package:riverpod/src/framework/provider_base.dart': 
Failed assertion: line 657 pos 7: '_debugDidChangeDependency == false': 
Cannot use ref functions after the dependency of a provider changed but before the provider rebuilt
```

**Comment by rrousselGit** [comment]
@pcelis19 Please provide a way to reproduce your issue. As mentioned before it could very well be that it's your code the problem

**Comment by Scheideba** [comment]
> For reference, this should be fixed in the 2.0.0 dev release.

This worked for me thank you

**Comment by sumanchapai** [comment]
For me, I noticed that i was using `watch` where I should have used `read`.

```
    ref
        .read(todayRoutineStatusProvider.state)
        .update((_) => TodayRoutineStatus.loading);
```

Was to be used instead of 
```
    ref
        .watch(todayRoutineStatusProvider.state)
        .update((_) => TodayRoutineStatus.loading);
```

**Comment by Yogesh-Dubey-Ayesavi** [comment]
> For information: This happens typically happens if you're using `ref.something` on a provider that was disposed.
> 
> It could be that you're using a `FutureProvider` like so:
> 
> ```dart
> final provider = FutureProvider((ref) {
>   ref.watch(foo);
>   await something();
>   ref.watch(bar);
> })
> ```
> 
> But during the `await something`, the provider was disposed (because `foo` changed), causing `ref.watch(bar)` to fail with this error

What should i do in this case?

**Comment by joachimbulow** [comment]
Just fyi this might also happen if you invalidate e.g. `provider a` and `provider b` in _one_ call and `provider a` watches `provider b`.
